// front-end/src/glossary.js
export const glossary = {
    variables:            "A named storage location in a program whose value can change during execution.",
    constants:            "A named value in a program that never changes once defined.",
    arithmetic:           "The basic math operations (addition, subtraction, multiplication, division) you perform on numbers.",
    functions:            "A reusable block of code that performs a specific task and can return a value.",
    rudiments:            "Fundamental or basic principles—think “the bare bones” of something.",
    pointers:             "A variable that holds the memory address of another variable.",
    structures:           "A composite data type in C that groups together variables under one name.",
    operators:            "Symbols such as +, -, *, / that perform mathematical, logical, or relational operations.",
    drawbacks:            "A disadvantage or negative side effect.",
    extrapolate:          "To infer or estimate something based on known information.",
    framework:            "A basic structure or skeleton on which more detailed features can be built.",
  
    // previously added:
    compile:              "To translate source code into machine‑readable instructions.",
    hurdle:               "A difficult obstacle or challenge.",
    UNIX:                 "A family of multitasking, multiuser computer operating systems originally developed at Bell Labs.",
    "operating system":   "Software that manages hardware resources and provides services to applications.",
    botched:              "Done badly or clumsily—a spoiling mistake.",
    omitting:             "Leaving something out or failing to include it.",
    compilation:          "The process of translating human‑readable source code into machine‑executable binary.",
    computation:          "The act of performing calculations or processing information.",
    subroutines:          "Named blocks of code that can be called from multiple places within a program.",
    Fortran:              "One of the earliest high‑level programming languages, designed for numeric and scientific computing.",
    Pascal:               "A structured programming language named after the mathematician Blaise Pascal.",
    "source files":       "Files containing human‑readable program code, typically ending in `.c` for C programs.",
    "Appendix B":         "Additional material at the end of a book providing supplementary information.",
    method:               "A way or technique of doing something.",
    arguments:            "Values passed into a function when it is called, used within that function.",
    function:             "A reusable block of code that performs a specific task and can return a value.",
    parentheses:          "The symbols `(` and `)` used to group expressions or parameters in code.",
    indicated:            "Made clear or shown; demonstrated.",
    enclosed:             "Surrounded or wrapped inside something else (e.g., code blocks in `{}` ).",
    compiler:             "A program that translates source code into machine code or bytecode.",
    error:                "A notification that something went wrong during compilation or execution.",
    stages:               "Steps or phases in a process.",
    identical:            "Exactly the same in every detail.",
    sequence:             "A series of characters or instructions arranged in a particular order.",
    extensible:           "Able to be expanded with new features without major changes.",
    mechanism:            "A method or process for accomplishing a specific task.",
  
    // newly requested terms:
    centigrade:           "A temperature scale where water freezes at 0° and boils at 100°.",
    declarations:         "Statements that introduce and specify the type of variables in code.",
    loops:                "Control structures that repeat a block of code as long as a condition holds.",
    formatted:            "Arranged according to a specified layout or style.",
    blank:                "An empty space character or an empty line in text.",
    integers:             "Whole numbers without fractional parts.",
    contrast:             "To compare in order to show differences.",
    float:                "A data type representing numbers with fractional parts.",
    "floating point":     "A way to represent real numbers with a fixed number of significant digits and an exponent.",
    fractional:           "Part of a number that comes after the decimal point.",
    int:                  "A data type representing integer values in C.",
    bits:                 "Binary digits, the smallest unit of data in computing (0 or 1).",
    bit:                  "A single binary digit, either 0 or 1.",
    objects:              "Instances of data types or structures in a program.",
    "machine-dependent":  "Behavior or properties that vary based on the hardware or system.",
    arrays:               "Ordered collections of elements of the same type stored in contiguous memory.",
    unions:               "C data structures that can hold different data types in the same memory location.",
    conversion:           "The act of changing a value from one form or type to another.",
    initial:              "Existing at the beginning; first assigned or set.",
    terminated:           "Ended, often indicated by a specific character or symbol.",
    semicolons:           "Characters (`;`) that mark the end of statements in many languages.",
    computed:             "Calculated or obtained by performing a computation.",
    condition:            "An expression that evaluates to true or false, controlling program flow.",
    body:                 "The block of code enclosed by braces that executes within a control structure.",
    converter:            "A program or function that transforms data from one form to another.",
    indent:               "Add spaces or tabs at the beginning of a line to improve readability.",
    indentation:          "The practice of adding spaces or tabs at the start of lines to show code structure.",
    emphasizes:           "Gives special importance or prominence to something.",
    logical:              "Based on formal principles of reasoning or truth values.",
    compilers:            "Programs that translate source code into executable machine code.",
    statement:            "A single instruction in a program.",
    dividing:             "Performing the arithmetic operation of division.",
    multiplying:          "Performing the arithmetic operation of multiplication.",
    truncates:            "Cuts off the fractional part of a number, discarding it.",
    discarded:            "Thrown away or removed; not kept.",
    "general-purpose":    "Designed for a wide range of uses rather than a specific task.",
    formatting:           "Applying a specific layout or style to text or data.",
    substituted:          "Replaced one element with another.",
    construction:         "A language feature or syntax form, such as a loop or function call.",
    corresponding:        "Matching or equivalent in position or function.",
    number:               "A mathematical value used in calculations.",
    type:                 "The classification of data that determines what values it can hold and how it behaves.",
    defined:              "Declared or given a specific meaning in code.",
    accessible:           "Available or reachable by a program or component.",
    ANSI:                 "American National Standards Institute, which defines formal specifications.",
    conforms:             "Adheres to a standard or specification.",
    "right-justified":    "Aligned so that text or numbers end at the same right-hand margin.",
    decimal:              "A base‑10 numbering system using digits 0–9.",
    operands:             "Values or variables on which an operator performs an operation.",
    operation:            "An action performed by an operator on one or more operands.",
    explicit:             "Clearly and fully expressed without leaving room for confusion.",
    fraction:             "The part of a number after the decimal point.",
    constrained:          "Limited or restricted by certain conditions.",
    hexadecimal:          "A base‑16 numbering system using digits 0–9 and letters A–F."
  };
  